language: python
python:
  - "3.6"

# install project dependencies
install:
  - pip install -r requirements.txt

script:
  #- python manage.py test
  - pylama

all_branches: true

notifications:
  email:
    on_success: never
    on_failure: always
