# Generated by Django 3.0.2 on 2020-01-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20200104_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
