# Generated by Django 3.0.2 on 2020-01-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_test_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
